api_authenticate:
    route: /api/authenticate/:username
    module: api
    action: authenticate
    parameters: [ ]
    csrf_enabled: false

api_status:
    route: /api/:api_username/status
    module: api
    action: status
    parameters: [ ]
    csrf_enabled: false

api_me:
    route: /api/:api_username/me
    module: api
    action: me
    parameters: [ ]
    csrf_enabled: false

api_list_projects:
    route: /api/:api_username/projects
    module: api
    action: listProjects
    parameters: [ ]
    csrf_enabled: false

api_list_issuetypes:
    route: /api/:api_username/issuetypes
    module: api
    action: listIssuetypes
    parameters: [ ]
    csrf_enabled: false

api_list_issuefields:
    route: /api/:api_username/list/issuefields/for/:project_key/type/:issuetype
    module: api
    action: listIssuefields
    parameters: [ ]
    csrf_enabled: false

api_list_fieldvalues:
    route: '/api/:api_username/list/fieldvalues/for/field/:field_key/*'
    module: api
    action: listFieldvalues
    parameters: [ ]
    csrf_enabled: false
